version: 2

dist: dist/iron-proxy

builds:
  - id: iron-proxy
    main: ./cmd/iron-proxy
    binary: iron-proxy
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X github.com/ironsh/iron-proxy/internal/version.Version={{.Version}}

archives:
  - id: iron-proxy
    ids:
      - iron-proxy
    formats: ["tar.gz"]
    name_template: "iron-proxy_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

dockers_v2:
  - id: iron-proxy
    ids:
      - iron-proxy
    images:
      - "ironsh/iron-proxy"
    tags:
      - "{{ .Version }}"
      - '{{ if not .Prerelease }}latest{{ end }}'
    dockerfile: Dockerfile.release

checksum:
  name_template: "checksums.txt"

release:
  prerelease: auto

changelog:
  sort: asc
